config/routes.rb
Rails.application.routes.draw do

  ########################################################################################################
  
  namespace :dashboard do
    
    controller :cursos do
      get '/cursos/gratis' => :gratis, as: :cursos_gratis
      post '/cursos/adquirir/:id' => :adquirir, as: :cursos_adquirir
    end
    resources :cursos, only: [:show, :index]
    
    controller :modulos do
    end
    resources :modulos, only: [:show]
    
    controller :provas do
    end
    resources :provas, only: [:show]
    
    controller :turmas do
      post '/turmas/inscrever_aluno/:id' => :inscrever_aluno, as: :turmas_inscrever_aluno
    end
    resources :turmas, only: [:show]
    
    controller :users do
    end
    resources :users 
    
    controller :pages do
      get '/home' => :home
      get '/perfil' => :perfil
    end

    root 'pages#home'
    get '*path' => redirect('/')
  end

  ########################################################################################################
  
  namespace :admin do
    
    controller :pages do
      get '/home' => :home
      get '/logs' => :logs
    end
    
    controller :categoria_cursos do
    end
    resources :categoria_cursos
    
    controller :cursos do
    end
    resources :cursos
    
    controller :modulos do
    end
    resources :modulos
    
    controller :provas do
    end
    resources :provas
    
    controller :turmas do
    end
    resources :turmas
    
    controller :users do
    end
    resources :users

    root 'pages#home'
    get '*path' => redirect('/')
  end

  ########################################################################################################
  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: "register"}

  authenticated :user do
    root 'dashboard/pages#home', as: :authenticated_root
  end

  controller :users do
  end
  resources :users

  controller :pages do
    get '/home' => :home
    get '/login' => :login
  end

  root 'pages#home'
  get '*path' => redirect('/')
  ########################################################################################################
end

app/models/prova.rb
class Prova < ApplicationRecord

  validates :descricao, :modulo, :responsavel, presence: true
  #validates :modulo, uniqueness: true

  validate :ter_perguntas

  belongs_to    :modulo
  belongs_to    :responsavel, :class_name => "User"
  has_many      :perguntas, dependent: :destroy
  accepts_nested_attributes_for :perguntas,  allow_destroy: true
  
  
  scope :ativos, -> {where("provas.ativo = #{true}")}

  after_create :log_for_create
  #after_update :log_for_update, unless: -> { self.changes.blank? }




  def ter_perguntas
    if self.perguntas.blank? and self.ativo 
      errors.add(:ops, '~> Para poder ativar esta prova, crie uma Pergunta.')
      return false
    end
    return true
  end

  def log_for_create
    Log.create(descricao: "Nova prova criada!", objeto: {"class" => "green", "id" => self.id, "tipo" => "provas", "descricao" => self.descricao})
  end

  def log_for_update
    Log.create(descricao: "Alteração na prova #{self.id} - #{self.descricao}", objeto: {"class" => "green", "id" => self.id, "tipo" => "provas", "descricao" => self.descricao}) 
  end

end

app/controllers/admin/provas_controller.rb
class Admin::ProvasController < Admin::ApplicationController
    before_action :set_prova, only: [:show, :edit, :update, :destroy, :add_pergunta]
      skip_before_action :verify_authenticity_token

    def index
      @modulo = Modulo.find(params[:modulo_id])
      @provas = @modulo.provas.order("created_at desc")
    end

    def show
    end

    def edit
      @modulo = Modulo.find(params[:modulo_id])
    end

    def update
        respond_to do |format|
            if @prova.update(prova_params)
                format.js {render inline: "M.toast({html: 'Atualizada!', classes: 'green'}); " }
            else
                format.js
            end
        end
    end

    def new
    	@prova = Prova.new
      @modulo = Modulo.find(params[:modulo_id])
      @prova.modulo_id = @modulo.id
      @prova.responsavel_id = current_user.id
    end

    def create
    	@prova = Prova.new(prova_params)
    	if @prova.save
            redirect_to edit_admin_prova_path(id: @prova.id, modulo_id: @prova.modulo_id), notice: "Prova #{@prova.descricao} criada com sucesso!"
        else
            respond_to do |format|
                format.js
            end
        end
    end

    def destroy
      l = Log.new(descricao: "Prova deletada!", objeto: {"id" => @prova.id, "tipo" => "provas", "descricao" => "#{@prova.descricao} deletada por (#{current_user.id}) #{nome}", "class" => "red", "user_id" => "#{current_user.id}"})
      if @prova.destroy
        l.save
        redirect_to request.referrer, notice: "Prova deletada!"
      else
        respond_to do |format|
          Log.new(descricao: "Tentativa de deletar Prova!", objeto: {"id" => @prova.id, "tipo" => "provas", "descricao" => "#{@prova.descricao} - Tentativa de (#{current_user.id}) #{nome}", "class" => "orange", "user_id" => "#{current_user.id}"})
          format.js {render inline: "M.toast({html: 'Não foi possível deletar o módulo #{@prova.descricao}', classes: 'red'}); " }
        end
      end
  end

  private

  def prova_params
      params.require(:prova).permit(:descricao, :ativo, :modulo_id, :tempo, :responsavel_id, {perguntas: {}},
                    perguntas_attributes: [:id, :frase, :tipos, :_destroy, 
                                          respostas_attributes: [:id, :frase, :correta, :_destroy]])
  end

  def set_prova
   @prova = Prova.find(params[:id])
end
end

app/controllers/dashboard/provas_controller.rb
class Dashboard::ProvasController < Dashboard::ApplicationController

  def show
    @prova = Prova.find(params[:id])
    @modulo = @prova.modulo
    @curso = @prova.modulo.curso
  end
end

app/helpers/prova_helper.rb
module ProvaHelper

	def pergunta_tipo
    Pergunta.tipos.map do |r, key|
     [I18n.t("pergunta.tipos.#{r}"), r]
    end
	end

end

app/views/admin/provas/_form.html.erb
<div class="">
	<%= form_for [:admin, @prova], remote: true do |f| %>
		<% if @prova.new_record? %>
			<%= f.text_field :modulo_id, type: "hidden"  %>
			<%= f.text_field :responsavel_id, type: "hidden"  %>
		<% end %>
		<div class="row">
			<div class="col s12 m12 l12">
				<div id="form_error">
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col s12 m12 l12">
				<nav>
					<div class="nav-wrapper green">
						<%= link_to "Cursos", admin_cursos_path(), class: " breadcrumb" %>
						<%= link_to truncate("#{@modulo.curso.nome}", length: 15), edit_admin_curso_path(@modulo.curso), class: " breadcrumb" %>
						<%= link_to "Módulos", admin_modulos_path(curso_id: @modulo.curso.id), class: " breadcrumb" %>
						<%= link_to truncate("#{@modulo.nome}", length: 15), edit_admin_modulo_path(id: @modulo.id, curso_id: @modulo.curso.id), class: " breadcrumb" %>
						<%= link_to "Provas".html_safe, admin_provas_path(modulo_id: @modulo.id), class: "breadcrumb" %>
						<% unless @prova.new_record? %>
							<%= link_to truncate("#{@prova.descricao}", length: 15), edit_admin_prova_path(id: @prova.id, modulo_id: @modulo.id), class: " breadcrumb" %>
						<% else %>
							<%= link_to "Nova Prova", new_admin_prova_path(modulo_id: @modulo.id), class: " breadcrumb" %>
						<% end %>

					</div>
				</nav><br>
			</div>
			<div class="col s12 m12 l12">
			<br>
				<div id="card_prova" class="card">
					<div class="card-content" style="border: 1px solid <%= action_controller(controller) == 'new_modulos' ? 'green' : '#2196f3' %>; padding: 15px; ">
						<div class="row"><br><br>
							<div class="field">
								<div class="input-field col s12 m12 l12">
									<i class="material-icons prefix">description</i>
									<%= f.text_field :descricao  %>
									<label for="prova_descricao">Descrição</label>
								</div>
							</div>
							<div class="field">
								<div class="input-field col s12 m12 l6">
									<i class="material-icons prefix">access_time</i>
									<%= f.text_field :tempo, :onkeypress => "mascara(this, checaNumero)" %>
									<label for="prova_tempo">Tempo para terminar (min)</label>
								</div>
							</div>
							<div class="field">
								<div class="input-field col s12 m12 l6">
									<label>
										<%= f.check_box :ativo, class: "filled-in checkbox"  %> 
										<span class="">Ativo</span>
									</label>
								</div>
							</div>
						</div>

						<div class="row">
							<div class="col s12 m12 l12">
						      <%= f.fields_for :perguntas do |pergunta| %>
						        <%= render 'pergunta_fields', f: pergunta %>
						      <% end %>
							</div>
						</div>
						<div class="row">
							<div class="col s12 m12 l12">
							    <%= link_to_add_association "Adicionar pergunta", f, :perguntas, class: 'btn shadow green medium' %>
							</div>
						</div>


						<div class="action">
							<button type="submit" class="send btn shadow green dark small right">Salvar</button>
							<a class="btn shadow blue dark small right margin-right-15">Visualizar</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/admin/provas/_list.html.erb
<table class="striped responsive-table">
  <thead>
    <tr>
      <th>Código</th>
      <th>Descrição</th>
      <th>Perguntas</th>
      <th>Ativo?</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody id="item_list">
    <%= render @provas %>
  </tbody>
</table>

app/views/admin/provas/_pergunta_fields.html.erb
<div class="nested-fields layout grey lighten-3 animated rubberBand">
	<%= link_to_remove_association "<i class='material-icons '>delete_sweep</i>".html_safe, f, class: 'btn f12 right shadow red medium' %>

	<div class="row">
		<div class="field">
			<div class="input-field col s12 m12 l12">
				<span class="span">Frase da Pergunta</span>
				<%= f.text_field :frase, placeholder: "Frase da pergunta"  %>
			</div>
		</div>

		<div class="field">
			<div class="input-field col s12 m12 l12">
				<%= f.collection_select :tipos, pergunta_tipo, :last, :first, { prompt: "Selecionar Tipo" } %>
				<%= f.label :tipos %>
			</div>
		</div>

	</div>
	<span class="span">Respostas</span>
	<div class="row">
		<%= f.fields_for :respostas do |resposta| %>
			<div class="col s12 m12 l6">
				<%= render 'resposta_fields', f: resposta %>
			</div>
		<% end %>
	</div>
	<div class="row">
		<div class="col s12 m12 l12">
		<%= link_to_add_association "Adicionar resposta", f, :respostas, class: 'btn shadow blue medium' %>
		</div>
	</div>

</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('select').formSelect();
  });
</script>

app/views/admin/provas/_prova.html.erb
<tr>
  <td class="cod">
    <span>
      <%= prova.id %>
    </span>
  </td>
  <td><%= "#{prova.descricao}" %></td>
  <td><%= "#{prova.perguntas.size}" %></td>
  <td>
    <%= prova.ativo ? "<i class='material-icons green-text'>check_box</i>".html_safe : "<i class='material-icons red-text'>check_box_outline_blank</i>".html_safe %>
  </td>
  <td class="actions">
    <%= link_to edit_admin_prova_path(id:prova.id, modulo_id: @modulo.id), class: "btn shadow blue small", title: "Editar #{prova.descricao}", 'data-toggle' => 'tooltip', 'data-placement' => 'top' do %>
      <i class='material-icons'>edit</i>
    <% end %>
    <%= link_to admin_prova_path(prova), class: "btn shadow orange small", title: "Visualizar #{prova.descricao}", 'data-toggle' => 'tooltip', 'data-placement' => 'top' do %>
      <i class='material-icons'>search</i>
    <% end %>
  </td>
</tr>

app/views/admin/provas/_resposta_fields.html.erb
<div class="nested-fields layout claro animated rubberBand">
  <%= link_to_remove_association "<i class='material-icons '>delete_sweep</i>".html_safe, f, class: 'btn f12 right shadow red medium' %>

  <div class="row">
    <div class="field">
      <div class="input-field col s12 m12 l12">
        <span class="span">Frase da Resposta</span>
        <%= f.text_field :frase, placeholder: "Frase da resposta"  %>
      </div>
    </div>
    <div class="field">
      <div class="input-field col s12 m12 l12">
        <label>
          <%= f.check_box :correta, class: "filled-in checkbox"  %> 
          <span class="">Correta</span>
        </label>
      </div>
    </div>
  </div>

</div>

app/views/admin/provas/add_pergunta.js.erb
<% if @prova.errors.any? %>
	<% @prova.errors.full_messages.each do |msg| %>
		M.toast({html: '<%= msg %>', classes: 'red'});
	<% end %>
<% end %>

app/views/admin/provas/create.js.erb
<% if @prova.errors.any? %>
	<% @prova.errors.full_messages.each do |msg| %>
		M.toast({html: '<%= msg %>', classes: 'red'});
	<% end %>
<% end %>

app/views/admin/provas/edit.html.erb
<%= render "form" %>

app/views/admin/provas/index.html.erb
<div class="row"></div>
<div class="row">
	<div class="col s12 m12 l12">
		<nav>
			<div class="nav-wrapper green">
				<%= link_to "Cursos", admin_cursos_path(), class: " breadcrumb" %>
				<%= link_to truncate("#{@modulo.curso.nome}", length: 15), edit_admin_curso_path(@modulo.curso), class: " breadcrumb" %>
				<%= link_to "Módulos", admin_modulos_path(curso_id: @modulo.curso.id), class: " breadcrumb" %>
				<%= link_to truncate("#{@modulo.nome}", length: 15), edit_admin_modulo_path(id: @modulo.id, curso_id: @modulo.curso.id), class: " breadcrumb" %>
				<%= link_to "Provas".html_safe, admin_provas_path(modulo_id: @modulo.id), class: "breadcrumb" %>

			</div>
		</nav><br>
		<%= link_to "Nova Prova".html_safe, new_admin_prova_path(modulo_id: @modulo.id), class: "btn shadow green" %>
	</div>
	<div class="col s12 m12 l12">
		<div class="card">
			<div class="card-content">
				<div class="row">
					<div class="col s12 m12 l12">
						<div id="prova_list">
							<%= render "list" %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/admin/provas/index.js.erb
$("#prova_list").html("<%= j( render 'list'  )%>");

app/views/admin/provas/new.html.erb
<%= render "form" %>

app/views/admin/provas/show.html.erb
<div class="">
	<div class="row">
		<% @prova.attributes.each do |key, value| %>
			<div class="col s12 m12 l6">

			      <div class="card white">
			        <div class="card-content black-text" style="min-height: 100px;">
					<strong><%= "#{key}".titleize %>: </strong> <%= (value.class == TrueClass) ? "<i class='material-icons green-text'>check_box</i>".html_safe : (value.class == FalseClass) ? "<i class='material-icons red-text'>close</i>".html_safe : "#{ value}" %>	
			        </div>
			      </div>

			</div>
		<% end %>
	</div>
</div>

app/views/admin/provas/update.js.erb
<% if @prova.errors.any? %>
	<% @prova.errors.full_messages.each do |msg| %>
		M.toast({html: '<%= msg %>', classes: 'red'});
	<% end %>
<% end %>