config/routes.rb
Rails.application.routes.draw do

  ########################################################################################################
  
  namespace :dashboard do
    
    controller :cursos do
      get '/cursos/gratis' => :gratis, as: :cursos_gratis
      post '/cursos/adquirir/:id' => :adquirir, as: :cursos_adquirir
    end
    resources :cursos, only: [:show, :index]
    
    controller :modulos do
    end
    resources :modulos, only: [:show]
    
    controller :provas do
    end
    resources :provas, only: [:show]
    
    controller :turmas do
      post '/turmas/inscrever_aluno/:id' => :inscrever_aluno, as: :turmas_inscrever_aluno
    end
    resources :turmas, only: [:show]
    
    controller :users do
    end
    resources :users 
    
    controller :pages do
      get '/home' => :home
      get '/perfil' => :perfil
    end

    root 'pages#home'
    get '*path' => redirect('/')
  end

  ########################################################################################################
  
  namespace :admin do
    
    controller :pages do
      get '/home' => :home
      get '/logs' => :logs
    end
    
    controller :categoria_cursos do
    end
    resources :categoria_cursos
    
    controller :cursos do
    end
    resources :cursos
    
    controller :modulos do
    end
    resources :modulos
    
    controller :provas do
    end
    resources :provas
    
    controller :turmas do
    end
    resources :turmas
    
    controller :users do
    end
    resources :users

    root 'pages#home'
    get '*path' => redirect('/')
  end

  ########################################################################################################
  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: "register"}

  authenticated :user do
    root 'dashboard/pages#home', as: :authenticated_root
  end

  controller :users do
  end
  resources :users

  controller :pages do
    get '/home' => :home
    get '/login' => :login
  end

  root 'pages#home'
  get '*path' => redirect('/')
  ########################################################################################################
end

app/models/curso.rb
class Curso < ApplicationRecord

  validates :nome, :categoria, :responsavel, presence: true
  validates :nome, uniqueness: true

  validate :ter_modulos

  belongs_to :categoria, :class_name => "CategoriaCurso"
  belongs_to :responsavel, :class_name => "User"
  has_many :modulos, dependent: :destroy
  has_many :turmas, dependent: :destroy

  mount_uploader :imagem_capa, ImagemUploader

  scope :ativos, -> {where("cursos.ativo = #{true}")}

  attr_accessor :custo, :preco, :desconto, :total

  after_create :log_for_create
  #after_update :log_for_update, if: -> { self.changes }

  def initialize(attributes = {})

    unless attributes.blank? 
      total = attributes[:total]
      attributes.merge!(:historico                                            => {"#{DateTime.now}" => Hash[attributes]}  )
      attributes.merge!(:valores                                              => {'CUSTO' => attributes[:custo], 'PRECO' => attributes[:preco], 'DESCONTO' => attributes[:desconto], 'TOTAL' => attributes[:total]}  )
      if total.to_f > 0
        attributes.merge!(:gratis                                            => false)
      else
        attributes.merge!(:gratis                                            => true)
      end
    end
    super
  end

  def update(attributes = {})

    total = attributes["total"] || self.valores["TOTAL"]
    attributes.merge!(ativo: "#{(["1", "true"].include?attributes['ativo'].to_s ) ? true : false}") unless attributes['ativo'].blank?
    attributes.merge!(destaque: "#{(["1", "true"].include?attributes['destaque'].to_s ) ? true : false}") unless attributes['destaque'].blank?
    attributes.merge!(:valores                                              => {'CUSTO' => attributes["custo"], 'PRECO' => attributes["preco"], 'DESCONTO' => attributes["desconto"], 'TOTAL' => attributes["total"]}  ) if attributes[:valores].blank? and !attributes["preco"].blank?
    attributes.select { |x| attributes.delete(x) if ["custo", "preco", "desconto", "total"].include?(x) } 
    historico = attributes.select { |key, value| {key => value} if "#{value}" != "#{self.attributes.with_indifferent_access[key]}" }.except("imagem_capa", "updated_at")
    attributes.merge!(:historico                                            => {"#{DateTime.now}" => historico}.merge(self.historico)   )
    if total.to_f > 0
      attributes.merge!(gratis: false)
    else
      attributes.merge!(gratis: true)
    end
    super    
  end

  def ter_modulos
    if self.modulos.blank? and self.ativo 
      errors.add(:ops, '~> Para poder ativar este curso, crie um Módulo.')
      return false
    end
    return true
  end

  def log_for_create
    Log.create(descricao: "Novo curso criado!", objeto: {"class" => "green", "id" => self.id, "tipo" => "cursos", "descricao" => self.nome})
  end

  def log_for_update
    Log.create(descricao: "Alteração no curso #{self.id} - #{self.nome}", objeto: {"class" => "green", "id" => self.id, "tipo" => "cursos", "descricao" => self.nome}) 
  end
  
end

app/controllers/admin/cursos_controller.rb
class Admin::CursosController < Admin::ApplicationController
    before_action :set_curso, only: [:show, :edit, :update, :destroy]
      skip_before_action :verify_authenticity_token

    def index
        conditions = []
        conditions << "cursos.id IN (#{params[:id].split(/\W+/).uniq.join(', ')})" unless params[:id].blank?
        conditions << "cursos.nome LIKE '%#{params[:nome]}%'" unless params[:nome].blank?
        @cursos = Curso.where(conditions.join(" AND ")).order("created_at desc")
    end

    def show
    end

    def edit
    end

    def update
      if @curso.update(curso_params)
        if params[:curso][:imagem_capa].blank?
          respond_to do |format|
            format.js {render inline: "M.toast({html: 'Atualizado!', classes: 'green'}); " }
          end
        else
          redirect_to request.referrer, notice: "Atualizado"
        end
      else
        respond_to do |format|
          format.js
        end
      end
    end

    def new
    	@curso = Curso.new
    end

    def create
    	@curso = Curso.new(curso_params)
    	if @curso.save
            redirect_to edit_admin_curso_path(@curso), notice: "Curso #{@curso.nome} criado com sucesso!"
        else
            respond_to do |format|
                format.js
            end
        end
    end

    def destroy
      if @curso.modulos.size > 0
        Log.create(descricao: "Tentativa de deletar Curso!", objeto: {"id" => @curso.id, "tipo" => "cursos", "descricao" => "#{@curso.nome} - Tentativa de (#{current_user.id}) #{nome}", "class" => "orange", "user_id" => "#{current_user.id}"})
        respond_to do |format|
          format.js {render inline: "M.toast({html: 'Não foi possível deletar o curso #{@curso.nome}, módulos existentes.', classes: 'red'}); " }
        end
      else
        l = Log.new(descricao: "Curso deletado!", objeto: {"id" => @curso.id, "tipo" => "cursos", "descricao" => "#{@curso.nome} deletada por (#{current_user.id}) #{nome}", "class" => "red", "user_id" => "#{current_user.id}"})
        if @curso.destroy
          l.save
        else
          respond_to do |format|
            Log.create(descricao: "Tentativa de deletar Curso!", objeto: {"id" => @curso.id, "tipo" => "cursos", "descricao" => "#{@curso.nome} - Tentativa de (#{current_user.id}) #{nome}", "class" => "orange", "user_id" => "#{current_user.id}"})
            format.js {render inline: "M.toast({html: 'Não foi possível deletar o curso #{@curso.nome}, módulos existentes.', classes: 'red'}); " }
          end
        end 
      end
  end

  private

  def curso_params
      params.require(:curso).permit(:nome, :descricao, :ativo, {permitidos: []}, :gratis, :destaque, :vitalicio, :ementa, :imagem_capa, 
                                    :responsavel_id, :categoria_id, :preco, :custo, :desconto, :total)
  end

  def set_curso
   @curso = Curso.find(params[:id])
  end
end

app/controllers/dashboard/application_controller.rb
class Dashboard::ApplicationController < ActionController::Base
	before_action :authenticate_user!
	load_and_authorize_resource
	protect_from_forgery with: :exception
	before_action :store_user_location!, if: :storable_location?
	rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
	include UserHelper
	
	layout 'dashboard'


	rescue_from CanCan::AccessDenied do |exception|
		flash[:alert] = "Você não tem permissão para acessar!"
		redirect_back(fallback_location: root_url)
	end

	private

	def record_not_found
		flash[:alert] = "Você está tentando acessar algo que não existe."
		redirect_back(fallback_location: root_url)
	end

	def storable_location?
		request.get? && is_navigational_format? && !devise_controller? && !request.xhr? 
	end

	def store_user_location!
	  # :user is the scope we are authenticating
	  store_location_for(:user, request.fullpath)
	end

  def after_sign_out_path_for(resource_or_scope)
  	stored_location_for(resource_or_scope) || super
  end




  end

app/controllers/dashboard/cursos_controller.rb
class Dashboard::CursosController < Dashboard::ApplicationController

  def index
    conditions = []
    conditions << "cursos.categoria_id IN (#{params[:categoria_id].split(/\W+/).uniq.join(', ')})" unless params[:categoria_id].blank?
    conditions << "cursos.ativo = #{true}"
    @cursos = Curso.where(conditions.join(' AND ')).order("created_at desc")
    authorize! :read,    Curso
  end

  def show
    @curso = Curso.find(params[:id])
  end

  def gratis
  end

  def adquirir
  	@curso = Curso.find(params[:id])
    if current_user.adquirir_curso!(@curso)
      redirect_to request.referrer, notice: 'Curso Adquirido!'
    else
      redirect_to request.referrer, alert: "Não foi possível Adquirir o curso #{@curso.nome}"
    end
  end

end

app/controllers/dashboard/modulos_controller.rb
class Dashboard::ModulosController < Dashboard::ApplicationController

  def show
    @modulo = Modulo.find(params[:id])
    @curso = @modulo.curso
  end
end

app/controllers/dashboard/pages_controller.rb
class Dashboard::PagesController < Dashboard::ApplicationController
    def home
    end
end

app/controllers/dashboard/provas_controller.rb
class Dashboard::ProvasController < Dashboard::ApplicationController

  def show
    @prova = Prova.find(params[:id])
    @modulo = @prova.modulo
    @curso = @prova.modulo.curso
  end
end

app/controllers/dashboard/turmas_controller.rb
class Dashboard::TurmasController < Dashboard::ApplicationController
  before_action :set_turma, only: [:show, :inscrever_aluno]


  def show
    @curso = @turma.curso
  end

  def inscrever_aluno
    m = Matricula.new(aluno_id: current_user.id, turma_id: @turma.id)
    if @turma.fim_inscricao.to_date < Date.today
      respond_to do |format|
          format.js {render inline: "M.toast({html: 'Tempo para inscrição terminou.', classes: 'red'}); " }
      end
    elsif m.save
  		redirect_to dashboard_curso_path(@turma.curso), notice: "Inscrito - #{@turma.descricao}"
  	else
      respond_to do |format|
          format.js {render inline: "M.toast({html: '#{m.errors.full_messages.first}', classes: 'red'}); " }
      end
  	end
  end

  private

  def set_turma
   @turma = Turma.find(params[:id])
  end

end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < Dashboard::ApplicationController

  def update
    if current_user.update(user_params)
      if params[:user][:fotos].blank?
      respond_to do |format|
        format.js {render inline: "M.toast({html: 'Atualizado!', classes: 'green'}); " }
      end
      else
        redirect_to request.referrer, notice: "Atualizado"
      end
    else
      respond_to do |format|
        format.js {render inline: "M.toast({html: '#{current_user.errors.messages}', classes: 'red'}); " }
      end
    end
  end

  private

  def user_params
      params.require(:user).permit(:nome, :email, :password, :celular, :telefone, :cpf, :rg, :data_nascimento, {fotos: []})
  end

end

app/helpers/curso_helper.rb
module CursoHelper
	def capa curso
		if curso.imagem_capa.blank?
			return "/images/tecnologia/#{rand(1..17)}.jpg"
		else
			return curso.imagem_capa.fill_medium
		end
	end

	def curso_novo? curso
		curso.created_at > DateTime.now-1.day
	end

	def custo curso
		curso.valores["CUSTO"].to_f
	end

	def preco curso
		if curso.valores["PRECO"].to_f.zero?
			return ""
		else
			return "R$ #{curso.valores["PRECO"].to_s.gsub('.','').to_f}"
		end
	end

	def total curso
		curso.valores["TOTAL"].to_f
	end

	def string_total curso
		if curso.valores["TOTAL"].to_f.zero?
			return "Grátis"
		else
			return "R$ #{curso.valores["TOTAL"].to_f}"
		end
	end

	def desconto curso
		curso.valores["DESCONTO"]
	end

	def total curso
		curso.valores["TOTAL"]
	end

	def form_id curso
		if curso.new_record?
			"new_curso"
		else
			"edit_curso_#{curso.id}"
		end
	end

	def cursos_gratis
		Curso.where(gratis: true, ativo: true)
	end

	def curso_gratis? curso
		curso.gratis
	end

	def curso_adquirido? curso
		current_user.cursos.keys.include?"#{curso.id}"
	end

	def cursos_de_turmas
		Curso.ativos.where(vitalicio: false)
	end

	def curso_vitalicio? curso
		curso.vitalicio
	end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/cursos/_curso_de_turma.html.erb
<li>
	<a class="btn green no-margin animated pulse infinite">Turmas</a>
</li>
<% @curso.turmas.each_with_index do |turma, index| %>
	<li>
		<%= link_to dashboard_turma_path(turma) do %>
			<%= "#{index+1} - " %><%= truncate("#{turma.descricao}", length: 25) %>
		<span class="span f10 right peso-3"> <i class="material-icons f10 prefix">access_time</i><%= turma_tempo_inscricao(turma) %> </span>
		<% end %>
	</li>
<% end %>

app/views/dashboard/cursos/_curso_vitalicio.html.erb
<% if curso_adquirido?(@curso) %>
	<li>
		<% if modulo_atual @curso %>
			<%= link_to "Continuar", dashboard_modulo_path((modulo_atual @curso)), class: "btn blue no-margin pulse animated pulse infinite" %>
		<% else %>
			<%= link_to "Começar", dashboard_modulo_path(@curso.modulos.order("ordem asc").first), class: "btn blue no-margin pulse animated pulse infinite" %>
		<% end %>
	</li>
	<% @curso.modulos.order("ordem asc").each do |modulo| %>
	<li>
		<a>
			<%= "#{modulo.ordem} - #{modulo.nome}" %>
			<span class="span f10 right peso-3"> <i class="material-icons f10 prefix">access_time</i> <%= "#{calcular_tempo modulo.tempo}" %></span>
		</a>
	</li>
	<% end %>
<% else %>
	<li>
		<%= link_to "Adquira já!", dashboard_cursos_adquirir_path(@curso), class: "btn green no-margin pulse", method: "post" %>
	</li>
	<% @curso.modulos.order("ordem asc").each do |modulo| %>
		<li>
			<a>
				<%= "#{modulo.ordem} - #{modulo.nome}" %>
			<span class="span f10 right peso-3"> <i class="material-icons f10 prefix">access_time</i> <%= "#{calcular_tempo modulo.tempo}" %></span>
			</a>
		</li>
	<% end %>
<% end %>

app/views/dashboard/cursos/_listar.html.erb
<div class="row">
	<% cursos.each_with_index do |curso, index| %>
	<!-- ############ SEPARAR LINHAS ############# -->
		<% if (index % 3) == 0 %>
			</div><div class="row">
		<% end %>
	<!-- ############ ############## ############# -->
		<div class="col s12 m4 l4">
	      <div class="card animated zoomInDown" style="min-height: 400px;" >
	          <%= link_to dashboard_curso_path(curso), class: "hover-image" do %>
	        <div class="card-image">
	          <% if is_new?curso %>
	          	<% if curso_novo? curso %>
		          <span class="badge green white-text left" style="position: relative; z-index: 99;">novo
		          </span>
	          	<% end %>
	          		<% if curso_adquirido? curso %>
						<span class="badge grey white-text" style="position: relative; z-index: 99;">Adquirido
						</span>
	          		<% else %>
						<span class="badge <%= curso_gratis?(curso) ? 'purple' : 'amber' %> white-text" style="position: relative; z-index: 99;"><%= string_total(curso) %>
						</span>
	          		<% end %>
	          <% end %>
	          <img src="<%= capa(curso) %>" style="display: initial; margin-top: -22px;">
	          <span class="card-title black-text f20" style="text-shadow: 0 0 5px rgba(000, 000, 000, 0.5); border-radius: 6px; background-color: rgba(255, 255, 255, .8); margin-bottom: -5px;  padding: 15px 15px 0 15px; width: 100%;"><%= truncate("#{curso.nome}", length: 30) %> <br>
	          	<span class="f12 no-padding no-margin" style="text-shadow: none !important; margin-top: -5px;"><%= curso.categoria.nome %></span>
	          </span>
	        </div>
	          <% end %>
	        <div class="card-content">
	          <p><%= truncate("#{curso.descricao}", length: 100) %></p>
	        </div>
	      </div>
		</div>		
	<% end %>
</div>

app/views/dashboard/cursos/gratis.html.erb
<h1 class="span"><%= pluralize(cursos_gratis.size, "Curso", "Cursos") %></h1>
<%= render "listar", cursos: cursos_gratis %>

app/views/dashboard/cursos/index.html.erb
<h1 class="span"><%= pluralize(@cursos.size, "Curso", "Cursos") %></h1>
<%= render "listar", cursos: @cursos %>

app/views/dashboard/cursos/show.html.erb
<nav id="slideout-modulos" class="transparent" >
	<div class="nav-wrapper transparent"><br>
		<a data-target="slide-modulos" class="sidenav-trigger btn shadow blue no-margin margin-bottom-15 right">Módulos</a>
	</div>
</nav>
<div class="row">
	<div class="col s12 m12 l8 ">
		<h1 class="f30 no-margin"><%= "#{@curso.nome} (#{@curso.categoria.nome})" %></h1>
		<br>
		<p style="padding: 0 15px;">
			<p>
				<%= "#{@curso.ementa}".html_safe %>
			</p>
			<p>
				<strong>Professor: </strong> <%= nome(@curso.responsavel) %>
			</p>
			<p>
				<% if @curso.gratis %>
					<span class="green-text" style="font-weight: 700;"><%= "#{string_total @curso}" %></span>
				<% else %>
					<strong>Preço: </strong> 
					<% unless (preco @curso).to_s == (string_total @curso).to_s %>
						<span class="grey-text" style="text-decoration: line-through;">	<%= "(#{preco @curso})" %> </span> 
					<% end %>
					&nbsp; 
					<span class="green-text" style="font-weight: 700;"><%= "#{string_total @curso}" %></span>
				<% end %>
			</p>
		</p>
	</div>
	<div class="col s12 m12 l4 no-margin no-padding">
		<ul id="slide-modulos" class="sidenav sidenav-fixed blue lighten-5 right-aligned" style="transform: translateX() !important;">
			<li>
				<div class="user-view">
					<div class="background black">
						<img src="<%= capa(@curso) %>" style="opacity: 0.1;">
					</div>
					<%= link_to dashboard_curso_path(@curso), class: "no-margin no-padding" do %>
						<img class="item circle" src="<%= capa(@curso) %>">
						<span class=" white-text name"><%= truncate("#{@curso.nome}", length: 30) %></span>
						<span class="item white-text name"><%= truncate("#{@curso.descricao}", length: 100) %></span>
					<% end %>
				</div>
			</li>
			<% if curso_vitalicio?(@curso) %>
				<%= render "curso_vitalicio" %>
			<% else %>
				<%= render "curso_de_turma" %>
			<% end %>
		</ul>
	</div>
</div>