config/routes.rb
Rails.application.routes.draw do

  ########################################################################################################
  
  namespace :dashboard do
    
    controller :cursos do
      get '/cursos/gratis' => :gratis, as: :cursos_gratis
      post '/cursos/adquirir/:id' => :adquirir, as: :cursos_adquirir
    end
    resources :cursos, only: [:show, :index]
    
    controller :modulos do
    end
    resources :modulos, only: [:show]
    
    controller :provas do
    end
    resources :provas, only: [:show]
    
    controller :turmas do
      post '/turmas/inscrever_aluno/:id' => :inscrever_aluno, as: :turmas_inscrever_aluno
    end
    resources :turmas, only: [:show]
    
    controller :users do
    end
    resources :users 
    
    controller :pages do
      get '/home' => :home
      get '/perfil' => :perfil
    end

    root 'pages#home'
    get '*path' => redirect('/')
  end

  ########################################################################################################
  
  namespace :admin do
    
    controller :pages do
      get '/home' => :home
      get '/logs' => :logs
    end
    
    controller :categoria_cursos do
    end
    resources :categoria_cursos
    
    controller :cursos do
    end
    resources :cursos
    
    controller :modulos do
    end
    resources :modulos
    
    controller :provas do
    end
    resources :provas
    
    controller :turmas do
    end
    resources :turmas
    
    controller :users do
    end
    resources :users

    root 'pages#home'
    get '*path' => redirect('/')
  end

  ########################################################################################################
  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: "register"}

  authenticated :user do
    root 'dashboard/pages#home', as: :authenticated_root
  end

  controller :users do
  end
  resources :users

  controller :pages do
    get '/home' => :home
    get '/login' => :login
  end

  root 'pages#home'
  get '*path' => redirect('/')
  ########################################################################################################
end

app/controllers/dashboard/application_controller.rb
class Dashboard::ApplicationController < ActionController::Base
	before_action :authenticate_user!
	load_and_authorize_resource
	protect_from_forgery with: :exception
	before_action :store_user_location!, if: :storable_location?
	rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
	include UserHelper
	
	layout 'dashboard'


	rescue_from CanCan::AccessDenied do |exception|
		flash[:alert] = "Você não tem permissão para acessar!"
		redirect_back(fallback_location: root_url)
	end

	private

	def record_not_found
		flash[:alert] = "Você está tentando acessar algo que não existe."
		redirect_back(fallback_location: root_url)
	end

	def storable_location?
		request.get? && is_navigational_format? && !devise_controller? && !request.xhr? 
	end

	def store_user_location!
	  # :user is the scope we are authenticating
	  store_location_for(:user, request.fullpath)
	end

  def after_sign_out_path_for(resource_or_scope)
  	stored_location_for(resource_or_scope) || super
  end




  end

app/controllers/dashboard/cursos_controller.rb
class Dashboard::CursosController < Dashboard::ApplicationController

  def index
    conditions = []
    conditions << "cursos.categoria_id IN (#{params[:categoria_id].split(/\W+/).uniq.join(', ')})" unless params[:categoria_id].blank?
    conditions << "cursos.ativo = #{true}"
    @cursos = Curso.where(conditions.join(' AND ')).order("created_at desc")
    authorize! :read,    Curso
  end

  def show
    @curso = Curso.find(params[:id])
  end

  def gratis
  end

  def adquirir
  	@curso = Curso.find(params[:id])
    if current_user.adquirir_curso!(@curso)
      redirect_to request.referrer, notice: 'Curso Adquirido!'
    else
      redirect_to request.referrer, alert: "Não foi possível Adquirir o curso #{@curso.nome}"
    end
  end

end

app/controllers/dashboard/modulos_controller.rb
class Dashboard::ModulosController < Dashboard::ApplicationController

  def show
    @modulo = Modulo.find(params[:id])
    @curso = @modulo.curso
  end
end

app/controllers/dashboard/pages_controller.rb
class Dashboard::PagesController < Dashboard::ApplicationController
    def home
    end
end

app/controllers/dashboard/provas_controller.rb
class Dashboard::ProvasController < Dashboard::ApplicationController

  def show
    @prova = Prova.find(params[:id])
    @modulo = @prova.modulo
    @curso = @prova.modulo.curso
  end
end

app/controllers/dashboard/turmas_controller.rb
class Dashboard::TurmasController < Dashboard::ApplicationController
  before_action :set_turma, only: [:show, :inscrever_aluno]


  def show
    @curso = @turma.curso
  end

  def inscrever_aluno
    m = Matricula.new(aluno_id: current_user.id, turma_id: @turma.id)
    if @turma.fim_inscricao.to_date < Date.today
      respond_to do |format|
          format.js {render inline: "M.toast({html: 'Tempo para inscrição terminou.', classes: 'red'}); " }
      end
    elsif m.save
  		redirect_to dashboard_curso_path(@turma.curso), notice: "Inscrito - #{@turma.descricao}"
  	else
      respond_to do |format|
          format.js {render inline: "M.toast({html: '#{m.errors.full_messages.first}', classes: 'red'}); " }
      end
  	end
  end

  private

  def set_turma
   @turma = Turma.find(params[:id])
  end

end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < Dashboard::ApplicationController

  def update
    if current_user.update(user_params)
      if params[:user][:fotos].blank?
      respond_to do |format|
        format.js {render inline: "M.toast({html: 'Atualizado!', classes: 'green'}); " }
      end
      else
        redirect_to request.referrer, notice: "Atualizado"
      end
    else
      respond_to do |format|
        format.js {render inline: "M.toast({html: '#{current_user.errors.messages}', classes: 'red'}); " }
      end
    end
  end

  private

  def user_params
      params.require(:user).permit(:nome, :email, :password, :celular, :telefone, :cpf, :rg, :data_nascimento, {fotos: []})
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/shared/dashboard/_navbar.html.erb
<nav>
  <div class="nav-wrapper">
    <a data-target="slide-out" class="sidenav-trigger"><i class="material-icons blue-text">menu</i></a>
    <span class="links">
      <i class="material-icons open-dialog purple-text">home</i>
      <i class="material-icons open-dialog blue-text">mail</i>
      <i class="material-icons open-dialog amber-text">perm_contact_calendar</i>
      <i class="material-icons open-dialog red-text">notifications</i>
      <i class="material-icons open-dialog green-text">help</i>
    </span>
    <div class="input-field hide-on-med-and-down">
      <input id="pesquisa" type="search">
      <label class="label-icon" for="search"><i class="material-icons">search</i></label>
      <i class="material-icons">close</i>
    </div>
  </div>
</nav>



<ul id="slide-out" class="sidenav sidenav-fixed " style="">
  <li>
    <div class="user-view">
      <div class="background-navbar black">
          <img src="/background-sidenav2.jpg" class="" >
      </div>
      <div class="profile animar-BounceInDown " >
        <a href="/dashboard/perfil">
          <img class="item circle animar-BounceInDown faster" src="<%= foto_perfil %>">
        </a>
          <a href="/dashboard/perfil">
            <span class="item white-text name animar-BounceInDown fast"><%= nome %></span>
          </a>
          <a href="/dashboard/perfil">
            <span class="item white-text email animar-BounceInDown"><%= email %></span>
          </a>
      </div>
    </div>
  </li>

  <li class="animar-BounceInLeft">
    <ul class="collapsible collapsible-accordion">
      <li class="<%= 'active' if is_home?(controller, @curso) %>">
        <%= link_to dashboard_root_path, class: "collapsible-header", style: "padding: 0 32px;" do %>
          Meus Cursos<i class="material-icons <%= 'blue-text' if action_name == 'home' %>">home</i><span class="badge green white-text"><%= user_cursos(current_user).size %></span>
        <% end %>
        <div class="collapsible-body">
          <ul style="padding-left: 15px;">
            <% user_cursos(current_user).each do |curso| %>
              <li><%= link_to dashboard_curso_path(curso) do %><%= truncate("#{curso.nome}", length: 16) %><i class="material-icons <%= 'blue-text' if !@curso.blank? and @curso.id == curso.id %>">import_contacts</i><% end %></li>
            <% end %>
          </ul>
        </div>
      </li>
    </ul>
  </li>


  <li class="animar-BounceInLeft">
    <ul class="collapsible collapsible-accordion">
      <li class="<%= 'active' if (['cursos'].include?controller_name and ['index', 'gratis'].include?action_name) %>">
        <%= link_to dashboard_cursos_path, class: "collapsible-header", style: "padding: 0 32px;" do %>
          Cursos<i class="material-icons <%= 'blue-text' if (['cursos'].include?controller_name and ['index', 'gratis'].include?action_name) %>">arrow_drop_down</i><span class="badge green white-text"><%= cursos.size %></span>
          <% end %>
        <div class="collapsible-body">
          <ul style="padding-left: 15px;">
              <li><%= link_to dashboard_cursos_path() do %>Todos<i class='material-icons <%= "#{'blue-text' if action_controller(controller) == 'index_cursos' and params[:categoria_id].blank?}" %>'>folder</i><% end %></li>
              <li><%= link_to dashboard_cursos_gratis_path() do %>Gratis<i class='material-icons <%= "#{'blue-text' if action_controller(controller) == 'gratis_cursos'}" %>'>folder</i><% end %></li>
              <% CategoriaCurso.all.each do |categoria| %>
                <li ><%= link_to dashboard_cursos_path(categoria_id: categoria.id) do %><%= categoria.nome %><i class='material-icons <%= "#{'blue-text' if categoria.id == params[:categoria_id].to_i}" %>'>folder</i><% end %></li>
              <% end %>
        </div>
      </li>
    </ul>
  </li>
  <li class="animar-BounceInLeft"><a>Minhas Anotações<i class='material-icons'>note_add</i></a></li>
  <li class="animar-BounceInLeft"><a>Rendimento<i class='material-icons'>insert_chart</i></a></li>
  <li class="animar-BounceInLeft"><a>Medalhas<i class='material-icons'>brightness_medium</i></a></li>
  <li class="animar-BounceInLeft"><a>Certificados<i class='material-icons'>card_membership</i></a></li>
  <li class="animar-BounceInLeft"><a>Materiais<i class='material-icons'>local_library</i></a></li>
  <li class="animar-BounceInLeft"><a>Simulados<i class='material-icons'>create</i></a></li>
  <li class="animar-BounceInLeft"><a>Eventos<i class='material-icons'>event</i></a></li>
  <li class="animar-BounceInLeft"><a>Perfil<i class='material-icons'>person</i></a></li>

  <hr>
  <li class="animar-BounceInLeft">
    <% if can? :acessar, :admin %>
      <%= link_to "Admin <i class='material-icons'>dashboard</i>".html_safe, admin_root_path %>
    <% end %>
  </li>
  <li class="animar-BounceInLeft"><%= link_to "Site <i class='material-icons'>home</i>".html_safe, home_path %></li>
  <li class="animar-BounceInLeft"><%= link_to "Sair <i class='material-icons'>exit_to_app</i>".html_safe, destroy_user_session_path, :method => :delete %></li>
</ul>


<script type="text/javascript">
  $(document).ready(function() {
    <% if action_name == "home" %>
      $(".animar-BounceInDown").addClass("animated bounceInDown");
      $(".animar-BounceInLeft").addClass("animated bounceInLeft");
      $(".animar-jello").addClass("animated jello");
    <% end %>
  });
</script>