config/routes.rb
Rails.application.routes.draw do

  ########################################################################################################
  
  namespace :dashboard do
    
    controller :cursos do
      get '/cursos/gratis' => :gratis, as: :cursos_gratis
      post '/cursos/adquirir/:id' => :adquirir, as: :cursos_adquirir
    end
    resources :cursos, only: [:show, :index]
    
    controller :modulos do
    end
    resources :modulos, only: [:show]
    
    controller :provas do
    end
    resources :provas, only: [:show]
    
    controller :turmas do
      post '/turmas/inscrever_aluno/:id' => :inscrever_aluno, as: :turmas_inscrever_aluno
    end
    resources :turmas, only: [:show]
    
    controller :users do
    end
    resources :users 
    
    controller :pages do
      get '/home' => :home
      get '/perfil' => :perfil
    end

    root 'pages#home'
    get '*path' => redirect('/')
  end

  ########################################################################################################
  
  namespace :admin do
    
    controller :pages do
      get '/home' => :home
      get '/logs' => :logs
    end
    
    controller :categoria_cursos do
    end
    resources :categoria_cursos
    
    controller :cursos do
    end
    resources :cursos
    
    controller :modulos do
    end
    resources :modulos
    
    controller :provas do
    end
    resources :provas
    
    controller :turmas do
    end
    resources :turmas
    
    controller :users do
    end
    resources :users

    root 'pages#home'
    get '*path' => redirect('/')
  end

  ########################################################################################################
  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: "register"}

  authenticated :user do
    root 'dashboard/pages#home', as: :authenticated_root
  end

  controller :users do
  end
  resources :users

  controller :pages do
    get '/home' => :home
    get '/login' => :login
  end

  root 'pages#home'
  get '*path' => redirect('/')
  ########################################################################################################
end

app/models/modulo.rb
class Modulo < ApplicationRecord

  validates :nome, :curso, presence: true
  validates :nome, uniqueness: { scope: :curso }

  belongs_to :curso
  has_many :provas

  mount_uploaders :materiais, DocumentoUploader
  skip_callback :commit, :after, :mark_remove_materiais_false
  skip_callback :commit, :after, :remove_previously_stored_materiais

  scope :ativos, -> {where("modulos.ativo = #{true}")}

  after_create :log_for_create
  #after_update :log_for_update, unless: -> { self.changes.blank? }

  def log_for_create
    Log.create(descricao: "Novo modulo criado!", objeto: {"class" => "green", "id" => self.id, "tipo" => "modulos", "descricao" => self.nome})
  end

  def log_for_update
    Log.create(descricao: "Alteração no modulo #{self.id} - #{self.nome}", objeto: {"class" => "green", "id" => self.id, "tipo" => "modulos", "descricao" => self.nome}) 
  end

end

app/controllers/admin/modulos_controller.rb
class Admin::ModulosController < Admin::ApplicationController
    before_action :set_modulo, only: [:show, :edit, :update, :destroy]
      skip_before_action :verify_authenticity_token

    def index
      conditions = []
      conditions << "modulos.id IN (#{params[:id].split(/\W+/).uniq.join(', ')})" unless params[:id].blank?
      conditions << "modulos.nome LIKE '%#{params[:nome]}%'" unless params[:nome].blank?
      unless params[:curso_id].blank?
        @curso = Curso.find(params[:curso_id]) 
        conditions << "modulos.curso_id = #{@curso.id}"
      end
      @modulos = Modulo.where(conditions.join(" AND ")).order("created_at desc")
    end

    def show
    end

    def edit
      @curso = @modulo.curso
    end

    def update
      if @modulo.update(modulo_params)
        if params[:modulo][:materiais].blank?
          respond_to do |format|
            format.js {render inline: "M.toast({html: 'Atualizado!', classes: 'green'}); " }
          end
        else
          redirect_to request.referrer, notice: "Atualizado!"
        end
      else
        respond_to do |format|
          format.js
        end
      end
    end

    def new
    	@modulo = Modulo.new
      unless params[:curso_id].blank?
        @curso = Curso.find(params[:curso_id])
        @modulo.curso_id = @curso.id
      end
    end

    def create
    	@modulo = Modulo.new(modulo_params)
    	if @modulo.save
            redirect_to edit_admin_modulo_path(id: @modulo.id, curso_id: @modulo.curso_id), notice: "Modulo #{@modulo.nome} criado com sucesso!"
        else
            respond_to do |format|
                format.js
            end
        end
    end

    def destroy
      l = Log.new(descricao: "Módulo deletado!", objeto: {"id" => @modulo.id, "tipo" => "modulos", "descricao" => "#{@modulo.nome} deletada por (#{current_user.id}) #{nome}", "class" => "red", "user_id" => "#{current_user.id}"})
    	if @modulo.destroy
        l.save
        redirect_to request.referrer, notice: "Módulo deletado!"
      else
        respond_to do |format|
          Log.new(descricao: "Tentativa de deletar Módulo!", objeto: {"id" => @modulo.id, "tipo" => "modulos", "descricao" => "#{@modulo.nome} - Tentativa de (#{current_user.id}) #{nome}", "class" => "orange", "user_id" => "#{current_user.id}"})
          format.js {render inline: "M.toast({html: 'Não foi possível deletar o módulo #{@modulo.nome}', classes: 'red'}); " }
        end
      end
  end

  private

  def modulo_params
      params.require(:modulo).permit(:nome, :descricao, :ativo, :curso_id, :conteudo, :tempo, :video, {materiais: []}, {curso_info: {}})
  end

  def set_modulo
   @modulo = Modulo.find(params[:id])
end
end

app/controllers/dashboard/modulos_controller.rb
class Dashboard::ModulosController < Dashboard::ApplicationController

  def show
    @modulo = Modulo.find(params[:id])
    @curso = @modulo.curso
  end
end

app/helpers/modulo_helper.rb
module ModuloHelper

	def modulo_atual curso
		mds = current_user.modulos_iniciados.where(modulo_id: curso.modulos.ids)
		if mds.blank?
			return false
		else
			return Modulo.where(id: mds.map {|mod| mod.modulo_id }).ordem("ordem asc").last
		end
	end
end

app/views/admin/modulos/_form.html.erb
<div class="">
	<%= form_for [:admin, @modulo], remote: true do |f| %>
		<div class="row">
			<div class="col s12 m12 l12">
				<div id="form_error">
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col s12 m12 l12">
				<nav>
					<div class="nav-wrapper green">
						<%= link_to "Cursos", admin_cursos_path(), class: " breadcrumb" %>
						<% unless @curso.blank? %>
							<%= link_to truncate("#{@curso.nome}", length: 15), edit_admin_curso_path(@curso), class: " breadcrumb" %>
							<%= link_to "Módulos", admin_modulos_path(curso_id: @curso.id), class: " breadcrumb" %>
						<% else %>
							<%= link_to "Módulos", admin_modulos_path, class: " breadcrumb" %>
						<% end %>
						<% if !@modulo.new_record? %>
							<%= link_to truncate("#{@modulo.nome}", length: 15), edit_admin_modulo_path(id: @modulo.id), class: " breadcrumb" %>
						<% elsif @curso.blank? %>
							<%= link_to "Novo Módulo", new_admin_modulo_path(), class: " breadcrumb" %>
						<% else %>
							<%= link_to "Novo Módulo", new_admin_modulo_path(curso_id: @curso.id), class: " breadcrumb" %>
						<% end %>
					</div>
				</nav><br>
				<% unless @modulo.new_record? %>
				<%= link_to "Visualizar Provas".html_safe, admin_provas_path(modulo_id: @modulo.id), class: "btn shadow green" %>
				<% end %>
			</div>
			<div class="col s12 m12 l12">
			<br>
				<div class="card">
						<div class="card-content" style="border: 1px solid <%= action_controller(controller) == 'new_modulos' ? 'green' : '#2196f3' %>; padding: 15px; ">
						<div class="row">
								<div class="field">
									<div class="input-field col s12 m12 l12">
										<i class="material-icons prefix">local_offer</i>
										<%= f.collection_select :curso_id, Curso.all.order("cursos.nome ASC"), :id, :nome, { prompt: "Selecionar Curso" } %>
										<%= f.label :curso %>
									</div>
								</div>
						</div>
						<div class="row">
							<div class="field">
								<div class="input-field col s12 m12 l12">
									<i class="material-icons prefix">description</i>
									<%= f.text_field :nome  %>
									<label for="modulo_nome">Nome</label>
								</div>
							</div>

							<div class="field">
								<div class="input-field col s12 m12 l12">
									<i class="material-icons prefix">description</i>
									<%= f.text_field :descricao %>
									<label for="modulo_descricao">Breve descrição do módulo</label>
								</div>
							</div>

							<div class="field">
								<div class="input-field col s12 m12 l6">
									<i class="material-icons prefix">access_time</i>
									<%= f.text_field :tempo, :onkeypress => "mascara(this, checaNumero)" %>
									<label for="modulo_tempo">Tempo para terminar (horas)</label>
								</div>
							</div>

							<div class="field">
								<div class="input-field col s12 m12 l6">
									<i class="material-icons prefix">ondemand_video</i>
									<%= f.text_field :video %>
									<label for="modulo_video">Video</label>
								</div>
							</div>

							<div class="field">
								<div class="input-field col s12 m12 l12">
									<label>
										<%= f.check_box :ativo, class: "filled-in checkbox"  %> 
										<span class="">Ativo</span>
									</label>
								</div>
							</div>
						</div>
						<div class="row layout claro" style="min-height: 200px;">
							<div class="col s12 m12 l6">
								<div class="file-field input-field">
									<div class="btn blue">
									    <span>MATERIAIS</span>
										<%= f.file_field :materiais, multiple: true %>
									</div>
									<div class="file-path-wrapper">
										<input class="validate" type="text" placeholder="Adiconar Materiais ">
									</div>
								</div>
							</div>
							<div class="col s12 m12 l6">
								<% @modulo.materiais.each do |material| %>
									<li>
										<a href="<%= material %>" target="_blank"><%= material.file.filename %></a>
									</li>
								<% end %>
							</div>
						</div>
						<div class="row">
							<div class="col s12 m12 l12">
								<div class="field">
									<div class="input-field col s12 m12 l12">
										<span class="f20 grey-text">Conteudo</span>
										<%= f.cktext_area :conteudo, as: :text, ckeditor: {language: 'pt'}  %>
									</div>
								</div>
							</div>
						</div>

						<div class="action ">
							<button type="submit" class="send btn shadow green dark small right">Salvar</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/admin/modulos/_list.html.erb
<table class="striped responsive-table">
  <thead>
    <tr>
      <th>Código</th>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Ativo?</th>
      <th>Prova?</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody id="item_list">
    <%= render @modulos %>
  </tbody>
</table>

app/views/admin/modulos/_modulo.html.erb
<tr>
  <td class="cod">
    <span>
      <%= modulo.id %>
    </span>
  </td>
  <td><%= "#{modulo.nome}" %></td>
  <td><%= modulo.descricao %></td>
  <td>
    <%= modulo.ativo ? "<i class='material-icons green-text'>check_box</i>".html_safe : "<i class='material-icons red-text'>check_box_outline_blank</i>".html_safe %>
  </td>
  <td>
    <%= modulo.provas.blank? ? "<i class='material-icons red-text'>check_box_outline_blank</i>".html_safe : "<i class='material-icons green-text'>check_box</i>".html_safe %>
  </td>
  <td class="actions">
    <%= link_to edit_admin_modulo_path(id:modulo.id), class: "btn shadow blue small", title: "Editar #{modulo.nome}", 'data-toggle' => 'tooltip', 'data-placement' => 'top' do %>
      <i class='material-icons'>edit</i>
    <% end %>
    <%= link_to admin_modulo_path(modulo), class: "btn shadow orange small", title: "Visualizar #{modulo.nome}", 'data-toggle' => 'tooltip', 'data-placement' => 'top' do %>
      <i class='material-icons'>search</i>
    <% end %>
  </td>
</tr>

app/views/admin/modulos/create.js.erb
<% if @modulo.errors.any? %>
	<% @modulo.errors.full_messages.each do |msg| %>
		M.toast({html: '<%= msg %>', classes: 'red'});
	<% end %>
<% end %>

app/views/admin/modulos/edit.html.erb
<%= render "form" %>

app/views/admin/modulos/index.html.erb
<div class="row">
<div class="row"></div>
	<div class="col s12 m12 l12">
		<nav>
			<div class="nav-wrapper green">
				<%= link_to "Cursos", admin_cursos_path(), class: " breadcrumb" %>
				<% unless @curso.blank? %>
					<%= link_to truncate("#{@curso.nome}", length: 15), edit_admin_curso_path(@curso), class: " breadcrumb" %>
					<%= link_to "Módulos", admin_modulos_path(curso_id: @curso.id), class: " breadcrumb" %>
				<% else %>
					<%= link_to "Módulos", admin_modulos_path(), class: " breadcrumb" %>
				<% end %>
			</div>
		</nav><br>
		<%= link_to "Novo Módulo".html_safe, new_admin_modulo_path(curso_id: params[:curso_id]), class: "btn shadow green" %>
	</div>
</div>

<div class="row layout">
	<div class="input-field col s12 m6 l3">
		<input id="codigo" type="text" class="validate">
		<label class="active" for="codigo">Código</label>
	</div>
	<div class="input-field col s12 m6 l3">
		<input id="name" type="text" class="validate">
		<label class="active" for="name">Nome</label>
	</div>
	<div class="input-field col s12 m6 l3">
		<a id="buscar" class="btn shadow black small">Buscar</a>
	</div>
</div>
<div class="row">
	
	<div class="col s12 m12 l12">
		<div class="card">
			<div class="card-content">
				<div class="row">
					<div class="col s12 m12 l12">
						<div id="modulo_list">
							<%= render "list" %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	$("#buscar").click(function(){
		$("#modulo_list").removeClass("animated tada");
		var codigo = $("#codigo").val();
		var nome = $("#nome").val();
		$.ajax({
			url: "/admin/modulos",
			method: "get",
			dataType: "script",
			data: {
				'id': 			codigo,
				'nome': 		nome
			}
		});
	});
$("input").keypress(function() {
    if (event.which == 13) $("a#buscar").trigger( "click" )
});
</script>

app/views/admin/modulos/index.js.erb
$("#modulo_list").html("<%= j( render 'list'  )%>").addClass("animated tada");

app/views/admin/modulos/new.html.erb
<%= render "form" %>

app/views/admin/modulos/show.html.erb
<div class="">
	<div class="row">
		<% @modulo.attributes.each do |key, value| %>
			<div class="col s12 m12 l6">

			      <div class="card white">
			        <div class="card-content black-text" style="min-height: 100px;">
					<strong><%= "#{key}".titleize %>: </strong> <%= (value.class == TrueClass) ? "<i class='material-icons green-text'>check_box</i>".html_safe : (value.class == FalseClass) ? "<i class='material-icons red-text'>close</i>".html_safe : "#{ value}" %>	
			        </div>
			      </div>

			</div>
		<% end %>
	</div>
</div>

app/views/admin/modulos/update.js.erb
<% if @modulo.errors.any? %>
	<% @modulo.errors.full_messages.each do |msg| %>
		M.toast({html: '<%= msg %>', classes: 'red'});
	<% end %>
<% end %>